// JavaScript Document

document.write("<div class='pd_menu_01'> ")
document.write("<ul><li><a href='index-2.html'>Home<!--[if IE 7]><!--></a><!--<![endif]--><!--[if lte IE 6]><table><tr><td><![endif]-->")
document.write("<!--[if lte IE 6]></td></tr></table></a><![endif]--></li></ul>	  ")

document.write("<ul><li><a href='Company/ourcompany-2.html'>Company<!--[if IE 7]><!--></a><!--<![endif]--><!--[if lte IE 6]><table><tr><td><![endif]-->")
document.write("<ul>")
document.write("<li><a href='Company/ourcompany_profile.html'>Profile</a></li>")
document.write("<li><a href='Company/ourcompany_management.html'  >Management</a></li>")
document.write("<li><a href='Company/ourcompany_careers.html'  class='lastone'>Careers</a></li>")
document.write("</ul>")
document.write("<!--[if lte IE 6]></td></tr></table></a><![endif]--></li></ul>")

document.write("<ul><li><a href='Services/ourservices-2.html'>Services<!--[if IE 7]><!--></a><!--<![endif]--><!--[if lte IE 6]><table><tr><td><![endif]-->")
document.write("<ul>")
document.write("<li><a href='Services/ourservices_IT-2.html'  >IT Services</a></li>")
document.write("<li><a href='Services/ourservices_security-2.html'  >Security Services</a></li>")
document.write("<li><a href='Services/ourservices_ites-2.html'  >ITES</a></li>")
document.write("<li><a href='Services/ourservices_cases.html'  class='lastone'>Case Studies</a></li>")
document.write("</ul>")
document.write("<!--[if lte IE 6]></td></tr></table></a><![endif]--></li></ul>")

document.write("<ul><li><a href='Products/ourproducts_it.html'>Products<!--[if IE 7]><!--></a><!--<![endif]--><!--[if lte IE 6]><table><tr><td><![endif]-->")
document.write("<ul>")
document.write("<li><a href='Products/ourproducts_it.html'  >IT Products</a></li>")
document.write("<li><a href='Products/ourproducts_security.html'  class='lastone'>Security Products</a></li>")
document.write("</ul>")
document.write("<!--[if lte IE 6]></td></tr></table></a><![endif]-->")
document.write("</li></ul>")

document.write("<ul><li><a href='contact/ouroffices.html'>Contact<!--[if IE 7]><!--></a><!--<![endif]--><!--[if lte IE 6]><table><tr><td><![endif]-->")
document.write("<ul>")
document.write("<li><a href='contact/ouroffices.html'>Offices</a></li>")
document.write("<li><a href='contact/downloads.html' class='lastone'>Downloads</a></li>")
document.write("</ul>")
document.write("<!--[if lte IE 6]></td></tr></table></a><![endif]--></li></ul>")
document.write("</ul>")
document.write("</div>")